// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uebocfnmkwvlhdbzuhqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlYm9jZm5ta3d2bGhkYnp1aHFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzA0NTIsImV4cCI6MjA3MzAwNjQ1Mn0.EumayleXLpauyviMcEe3h0txqPvfojJD6IHDCOuSQX0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});